#!/bin/bash

SKEY="signing-key/my-release-key.keystore"
APP="dist/cordova/android/apk/release/app-release-unsigned.apk"
SIGNEDDIR="dist/cordova/android/apk/signed"

jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore "$SKEY" "$APP" alias_name && zipalign -v 4 "$APP" "${1:-ziggiapp}".apk && { test ! -d $SIGNEDDIR && mkdir $SIGNEDDIR; }; mv -f "${1:-ziggiapp}".apk $SIGNEDDIR/"${1:-ziggiapp}".apk && echo "Signed App is at $SIGNEDDIR/${1:-ziggiapp}.apk"